spring:
  application:
    name: ${demo.cloud.applications.feign.id:feign-client}
server:
  port: ${demo.cloud.applications.feign.port:8083}
eureka:
  client:
    serviceUrl:
      defaultZone: ${demo.cloud.eureka:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true