server:
  port: ${demo.cloud.applications.gateway.port:8081}
eureka:
  client:
    serviceUrl:
      defaultZone: ${demo.cloud.eureka:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: ${demo.cloud.applications.gateway.id:gateway-server}
  cloud:
    gateway:
      routes:
        - id: path_router
          uri: lb://${demo.cloud.applications.user.id:user-provider}
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1