spring:
  application:
    name: ${demo.cloud.applications.user.id:user-provider}
server:
  port: ${demo.cloud.applications.user.port:0}
eureka:
  client:
    serviceUrl:
      defaultZone: ${demo.cloud.eureka:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true