spring:
  application:
    name: zuul-server
server:
  port: 8099
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
zuul:
  routes:
    user:
      path: /user/**
      serviceId: spring-cloud-user-provider
      stripPrefix: true