spring:
  application:
    name: ${demo.cloud.applications.zuul.id:zuul-server}
server:
  port: ${demo.cloud.applications.zuul.port:8082}
eureka:
  client:
    serviceUrl:
      defaultZone: ${demo.cloud.eureka:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
zuul:
  routes:
    user:
      path: /user/**
      serviceId: ${demo.cloud.applications.user.id:user-provider}
      stripPrefix: true